/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aidul.planify;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author FrenzYy
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        
        //        import icon
        Image icon = new ImageIcon("D:\\D3_TEKNIK_INFORMATIKA\\SEMESTER 3 (TIGA)\\PEMROGRAMAN VISUAL\\Planify\\src\\main\\resources\\icons/logo_planify.png").getImage();
        this.setIconImage(icon);
        
        // Mengambil nama dari UserSession yang sudah kita simpan saat Login
        String nama = UserSession.getUserName();
        lbl_nama_user.setText("Halo, " + nama + "!");
        
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nama_user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tugas = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        txt_deadline = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_judul = new javax.swing.JTextField();
        cmb_prioritas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_deskripsi = new javax.swing.JTextArea();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_nama_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nama_user.setForeground(new java.awt.Color(51, 51, 51));
        lbl_nama_user.setText("Halo, (Nama User)");
        lbl_nama_user.setPreferredSize(new java.awt.Dimension(126, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Profil Saya");
        jButton1.setPreferredSize(new java.awt.Dimension(103, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_cari.setPreferredSize(new java.awt.Dimension(73, 40));

        tbl_tugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Judul", "Deadline", "Prioritas", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_tugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tugas);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        txt_deadline.setPreferredSize(new java.awt.Dimension(73, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Judul:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Prioritas:");

        txt_judul.setPreferredSize(new java.awt.Dimension(73, 40));

        cmb_prioritas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_prioritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rendah", "Sedang", "Tinggi" }));
        cmb_prioritas.setPreferredSize(new java.awt.Dimension(74, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Deadline:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Deskripsi:");

        txt_deskripsi.setColumns(20);
        txt_deskripsi.setRows(5);
        jScrollPane2.setViewportView(txt_deskripsi);

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.setPreferredSize(new java.awt.Dimension(76, 40));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbl_nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_ubah)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_batal))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_simpan)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_hapus))))
                                .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_prioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_hapus))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ubah)
                            .addComponent(btn_batal))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int tanya = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);

        if (tanya == javax.swing.JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true); // Kembali ke Login
            this.dispose(); // Tutup Dashboard
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void tbl_tugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tugasMouseClicked
        int baris = tbl_tugas.rowAtPoint(evt.getPoint());

        // Ambil data dari tabel (Ingat urutan kolom di tampilkanData tadi)
        String judul = tbl_tugas.getValueAt(baris, 1).toString();
        String deadline = tbl_tugas.getValueAt(baris, 2).toString();
        String prioritas = tbl_tugas.getValueAt(baris, 3).toString();
        String deskripsi = tbl_tugas.getValueAt(baris, 5).toString(); // Ambil dari kolom tersembunyi

        // Masukkan ke Form Input
        txt_judul.setText(judul);
        txt_deadline.setText(deadline);
        cmb_prioritas.setSelectedItem(prioritas);
        txt_deskripsi.setText(deskripsi);
    }//GEN-LAST:event_tbl_tugasMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
    String sql = "INSERT INTO tasks (user_id, title, deadline, priority, status, description) VALUES (?, ?, ?, ?, ?, ?)";
    java.sql.Connection conn = DatabaseConnection.connect();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    // Set parameter
    pst.setInt(1, UserSession.getUserId());
    pst.setString(2, txt_judul.getText());
    // Pastikan format tanggal YYYY-MM-DD. Jika user input asal, ini bisa error (perlu validasi nanti)
    pst.setString(3, txt_deadline.getText()); 
    pst.setString(4, cmb_prioritas.getSelectedItem().toString());
    pst.setString(5, "Pending"); // Status default saat tugas baru
    pst.setString(6, txt_deskripsi.getText());
    
    pst.execute();
    javax.swing.JOptionPane.showMessageDialog(this, "Tugas Berhasil Disimpan!");
    
    tampilkanData(); // Refresh tabel
    kosongkanForm(); // Buat method ini nanti (lihat paling bawah)
    
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        try {
    // Cek apakah ada baris yang dipilih?
    int baris = tbl_tugas.getSelectedRow();
    if (baris == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih tugas di tabel dulu!");
        return;
    }

    // Ambil ID dari kolom 0 yang tersembunyi tadi!
    String idTugas = tbl_tugas.getValueAt(baris, 0).toString();

    String sql = "UPDATE tasks SET title=?, deadline=?, priority=?, description=? WHERE id=?";
    java.sql.Connection conn = DatabaseConnection.connect();
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    pst.setString(1, txt_judul.getText());
    pst.setString(2, txt_deadline.getText());
    pst.setString(3, cmb_prioritas.getSelectedItem().toString());
    pst.setString(4, txt_deskripsi.getText());
    pst.setString(5, idTugas); // Where ID = ...
    
    pst.execute();
    javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Diubah!");
    tampilkanData();
    kosongkanForm();
    
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Gagal Ubah: " + e.getMessage());
}
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
    int baris = tbl_tugas.getSelectedRow();
    if (baris == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih tugas yang mau dihapus!");
        return;
    }
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Hapus tugas ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        String idTugas = tbl_tugas.getValueAt(baris, 0).toString();
        
        String sql = "DELETE FROM tasks WHERE id=?";
        java.sql.Connection conn = DatabaseConnection.connect();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, idTugas);
        
        pst.execute();
        javax.swing.JOptionPane.showMessageDialog(this, "Tugas Dihapus!");
        tampilkanData();
        kosongkanForm();
    }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        kosongkanForm();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cmb_prioritas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_nama_user;
    private javax.swing.JTable tbl_tugas;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_deadline;
    private javax.swing.JTextArea txt_deskripsi;
    private javax.swing.JTextField txt_judul;
    // End of variables declaration//GEN-END:variables

    // Method untuk mengambil data tugas dari Database ke Tabel
    private void tampilkanData() {
    // Model Tabel
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    model.addColumn("ID");          // Kolom 0 (Hidden)
    model.addColumn("Judul");       // Kolom 1
    model.addColumn("Deadline");    // Kolom 2
    model.addColumn("Prioritas");   // Kolom 3
    model.addColumn("Status");      // Kolom 4
    model.addColumn("Deskripsi");   // Kolom 5 (Hidden baru!)
    
    tbl_tugas.setModel(model);
    
    // Sembunyikan ID (Kolom 0) DAN Deskripsi (Kolom 5) dari pandangan user
    tbl_tugas.getColumnModel().getColumn(0).setMinWidth(0);
    tbl_tugas.getColumnModel().getColumn(0).setMaxWidth(0);
    tbl_tugas.getColumnModel().getColumn(0).setWidth(0);
    
    tbl_tugas.getColumnModel().getColumn(5).setMinWidth(0);
    tbl_tugas.getColumnModel().getColumn(5).setMaxWidth(0);
    tbl_tugas.getColumnModel().getColumn(5).setWidth(0);

    try {
        java.sql.Connection conn = DatabaseConnection.connect();
        String sql = "SELECT * FROM tasks WHERE user_id = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, UserSession.getUserId()); 
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        while (rs.next()) {
            model.addRow(new Object[] {
                rs.getInt("id"),
                rs.getString("title"),
                rs.getDate("deadline"),
                rs.getString("priority"),
                rs.getString("status"),
                rs.getString("description") // Ambil deskripsi juga
            });
        }
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
}
    
    private void kosongkanForm() {
    // Mengosongkan semua kotak input
    txt_judul.setText("");
    txt_deadline.setText("");
    cmb_prioritas.setSelectedIndex(0); // Kembali ke pilihan pertama
    txt_deskripsi.setText("");
    
    // Menghilangkan sorotan (seleksi) pada tabel
    tbl_tugas.clearSelection();
}
    
}
